import { Grid2 } from '@mui/material'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Product Page',
  description: 'Generated by create next app',
}
export default function Products() {
  return (
    <Grid2 container style={{ backgroundColor: 'lightgray' }}>
      <h1>products page</h1>
    </Grid2>
  )
}
